name: Priya Mann
favicon: null
layout_spectrum: 0.9203257658518851
typography_spectrum: 0.08830489940010011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8102484196424484
  lightness: 0.5711872812826186
  saturation: 0.43918878003023565
  rhythmicContrast: 0.26738116005435586
purpose: []
