name: Priya Mann
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08830489940010011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161616'
    - '#da244d'
    - '#e1beaa'
    - '#ac7862'
  brandStrength: 0.8102484196424484
  lightness: 0.5711872812826186
  saturation: 0.43918878003023565
  rhythmicContrast: 0.26738116005435586
purpose: []
